# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  release: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: ./build.sh

      - name: Run a multi-line script
        run: |
          echo "Directory Listing"
          ls -al
          echo `ls -al`

      - name: version
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get_version

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.get_version.outputs.tag }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

