# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: build.sh

      - name: Run a multi-line script
        run: |
          echo "Directory Listing"
