# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main

jobs:
  release: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: ./build.sh

      - name: Run a multi-line script
        run: |
          echo "Directory Listing"
          ls -al
          echo `ls -al`

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: version

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: {{ steps.versiong.outputs.tag }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}


